// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJvzwsNFaKfedfTi-qIAPBi9061KRFTiE',
    appId: '1:595685465060:web:867eab5ab11d617a4645f1',
    messagingSenderId: '595685465060',
    projectId: 'lmcr-report',
    authDomain: 'lmcr-report.firebaseapp.com',
    storageBucket: 'lmcr-report.firebasestorage.app',
    measurementId: 'G-7MHMB1WL4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYUvVykPjSrhF2FE12eFajfDi2kDh7vTY',
    appId: '1:595685465060:android:b2af369d95fd510b4645f1',
    messagingSenderId: '595685465060',
    projectId: 'lmcr-report',
    storageBucket: 'lmcr-report.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvhPxk4z3xmYaBoQsLIqX6O3e6MZ2a9jw',
    appId: '1:595685465060:ios:b0040f4d24f0b4d54645f1',
    messagingSenderId: '595685465060',
    projectId: 'lmcr-report',
    storageBucket: 'lmcr-report.firebasestorage.app',
    iosBundleId: 'com.example.reportAirline',
  );

}